name: Test

on:
  push:
    branches:
      - main
      - staging
  pull_request:

env:
  RUBY_VERSION: 3.1.1
  NODE_VERSION: 18.17.1
    
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        ports:
          - 5432:5432
        env:
          RAILS_ENV: test
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: 119.0.6045.105
  
      - name: List Chrome
        run: apt list --installed | grep chrome
  
      - name: Remove Chrome
        run: sudo apt remove google-chrome-stable
  
      - uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 119.0.6045.105
  
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - run: bundle exec rubocop -P
        name: Lint Ruby files

      - name: Setup & create Database
        run: |
          bundle exec rails db:create db:schema:load
        env:
          RAILS_ENV: test
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres

      - name: Precompile assets
        run: |
          npm ci
          bundle exec rake assets:precompile
        env:
          RAILS_ENV: production
          DB_ADAPTER: nulldb
          SECRET_KEY_BASE: 1234567890

      - name: Run RSpec
        run: SIMPLECOV=1 CODECOV=1 bundle exec rspec
        env:
          RAILS_ENV: test
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres